mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

#python 2 supported
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        #Return last five published questions
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        #exludes questions that aren't published yet
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    
    
    
"""def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def detail (request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request,'polls/detail.html',{'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
"""

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.vote += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>DjangoPollSite</title>
    <meta charset="utf-8">
    
    {% load staticfiles %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/styleDetail.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/fonts/css/font-awesome.min.css' %}" />
    
    <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'polls/js/jquery-2.1.4.min.js' %}"></script>
    <!--<script src="{% static 'polls/js/jquery-1.11.13.min.js' %}"></script>-->

</head>
    
<body>

    <div id="container" class="container-fluid">
    <div class="row"><!--header row-->
        
    <header id="header" class="col-md-12 col-xs-12">
        
        <nav id="navigator" class="col-md-12">
            <div id="navLeft" class="col-xs-6">
                <a href="foo">Interphase</a>
            </div>
            <div id="navRight" class="col-xs-6">
                <a href="foo">Home</a>
                <a href="foo">Generic</a>
                <a href="foo">Elements</a>
            </div>
        </nav><!--end of nav-->

        <!--<h1>3 Ajankohtaista kysymystä</h1>
        <p>Vastaa ja voita!</p>
        <a href="foo">Aloita tästä</a>-->
        
    </header><!--end of header-->
    </div><!--end of row-->
    
    <div class="row"><!--mainContent row-->
    <article id="mainContent" class="col-md-12 col-xs-12">
        
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        <article id="pollContainer" class="col-md-8"> <!--polls after this!-->
            
            <i id="pollListIcon"class="fa fa-camera-retro fa-3x" ></i>
                
            <h1>{{ question.question_text }}</h1>

            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
            {% endfor %}
            <input type="submit" value="Vote" />
            </form>
        
        </article><!--end of polls-section-->
        
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        
    </article><!--end of mainContent-->
    </div><!--end of row-->
    
    <div class="row"><!--footer row-->
    <footer id="foot" class="col-lg-12 col-md-12">
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        
        <article class="col-md-8"><!--page info-->
            <div class="col-md-4 col-sm-4 col-xs-4">
                <table>    
                    <th id="footHeader">Lorem Ipsum</th>
                    <tr><td>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                </table>
            </div>
            
            <div class="col-md-4 col-sm-4 col-xs-4">
                <table>    
                    <th>Lorem Ipsum</th>
                    <tr><td>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                </table>
            </div>
            
            <div class="col-md-4 col-sm-4 col-xs-4">
                <table class="col-lg-12">
                    <th>Contact Us</th>
                    <tr>
                        <td id="socialTD">
                            <a id="social" href="http://www.twitter.com" class="fa fa-twitter fa-1x"></a>
                            <a id="social" href="http://www.facebook.com" class="fa fa-facebook fa-1x"></a>
                            <a id="social" href="http://www.plus.google.com" class="fa fa-google-plus fa-1x"></a>
                            <a id="social" href="http://www.pinterest.com" class="fa fa-pinterest fa-1x"></a>
                            <a id="social" href="http://www.linkedin.com" class="fa fa-linkedin fa-1x"></a>
                        </td>
                    </tr>
                    <tr>
                        <th>Address</th>
                        <td id="footerData">Torttukatu 24 </ br>00699 Hinurila</td>
                    </tr>
                    <tr>
                        <th>Mail</th>
                        <td id="footerData">contact@isis.com</td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td id="footerData">0700-allahu</td>
                    </tr>
                </table>
            </div>
        </article><!--end of pageinfo-->
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        
        <div id="copyFooter" class="col-md-12">
            <table>
                <tr>
                    <td>c Untitled. All right reserved</td><td>Design: Hippigay</td><td>Images: apina.biz</td>
                </tr>
            </table>
        </div>
    </footer><!--end of footer-->
    </div><!--end of row-->  
        
    </div><!-- end of container-->

</body>
</html>


<!--
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>-->

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>DjangoPollSite</title>
    <meta charset="utf-8">
    
    {% load staticfiles %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/fonts/css/font-awesome.min.css' %}" />
    
    <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'polls/js/jquery-2.1.4.min.js' %}"></script>
    <!--<script src="{% static 'polls/js/jquery-1.11.13.min.js' %}"></script>-->

</head>
    
<body>

    <div id="container" class="container-fluid">
        
    <div class="row"><!--header row-->
        
    <header id="header" class="col-md-12 col-xs-12">
        
        <nav id="navigator" class="col-md-12">
            <div id="navLeft" class="col-xs-6">
                <a href="foo">Interphase</a>
            </div>
            <div id="navRight" class="col-xs-6">
                <a href="foo">Home</a>
                <a href="foo">Generic</a>
                <a href="foo">Elements</a>
            </div>
        </nav><!--end of nav-->

        <h1>3 Ajankohtaista kysymystä</h1>
        <p>Vastaa ja voita!</p>
        <a href="foo">Aloita tästä</a>
        
    </header><!--end of header-->
    </div><!--end of row-->
    
    <div class="row"><!--mainContent row-->
    <article id="mainContent" class="col-md-12 col-xs-12">
        
        <p id="mainContentHeader">Vastaa näihin kolmeen kysymykseen</p>
        <p id="mainContentParagraph">Vastattuasi otamme sinuun ytheyttä ja voit olla uuden Ladan omistaja</p>
        
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        <article id="pollContainer" class="col-md-8"> <!--polls after this!-->
            
            <ul>
                <li id="pollListIcon" class="col-md-4 col-sm-4 col-xs-4"><i class="fa fa-camera-retro fa-3x" ></i></li >
                <li id="pollListIcon" class="col-md-4 col-sm-4 col-xs-4"><i class="fa fa-camera-retro fa-3x" ></i></li >
                <li id="pollListIcon" class="col-md-4 col-sm-4 col-xs-4"><i class="fa fa-camera-retro fa-3x" ></i></li >
            
            {% if latest_question_list %}
            {% for question in latest_question_list %}
                <li id="pollListItem" class="col-md-4 col-xs-4"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
            </ul>

            {% else %}
                <p>No polls are available</p>
            {% endif %}
        
        </article><!--end of polls-section-->
        
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        
    </article><!--end of mainContent-->
    </div><!--end of row-->
    
    <!-- RESPONSIIVISUUDET EI FUTAA VIELÄ-->
    <div class="row"><!--footer row-->
    <footer id="foot" class="col-lg-12 col-md-12">
        
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        
        <article class="col-md-8"><!--page info-->
            <div class="col-md-4 col-sm-4 col-xs-4">
                <div id="tableContainer">
                    <p id="footHeader"><strong>Lorem Ipsum</strong></p>
                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
                <table class="col-lg-12 col-md-12 col-xs-12">    
                    <tr><td>Höpöhpöpö</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                </table>
            </div>
            
            <div class="col-md-4 col-sm-4 col-xs-4">
                <div id="tableContainer">
                    <p id="footHeader"><strong>Lorem Ipsum</strong></p>
                    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div> 
                <table class="col-lg-12 col-md-12 col-xs-12">    
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                </table>
            </div>
            
            <div class="col-md-4 col-sm-4 col-xs-4">
                <div id="tableContainer">
                    <p><strong>Contact Us</strong></p>
                    <table class="col-lg-12 col-md-12 col-xs-12">
                        <tr>
                            <td>
                                <a id="social" href="http://www.twitter.com" class="fa fa-twitter fa-1x"></a></td>
                            <td>
                                <a id="social" href="http://www.facebook.com" class="fa fa-facebook fa-1x"></a></td>
                            <td>
                                <a id="social" href="http://www.plus.google.com" class="fa fa-google-plus fa-1x"></a></td>
                            <td>
                                <a id="social" href="http://www.pinterest.com" class="fa fa-pinterest fa-1x"></a></td>
                            <td>
                                <a id="social" href="http://www.linkedin.com" class="fa fa-linkedin fa-1x"></a></td>
                            </td>
                        </tr>
                    </table>
                </div>
                <table class="col-lg-12 col-md-12 col-xs-12" id="contactTable">
                    <tr>
                        <td><strong>Address</strong></td>
                        <td id="footerData">Torttukatu 24 </ br>00699 Hinurila</td>
                    </tr>
                    <tr>
                        <td><strong>Mail</strong></td>
                        <td id="footerData">contact@isis.com</td>
                    </tr>
                    <tr>
                        <td><strong>Phone</strong></td>
                        <td id="footerData">0700-allahu</td>
                    </tr>
                </table>
            </div>
        </article><!--end of pageinfo-->
    
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        <div class="col-md-3 col-sm-3 col-xs-3"></div><!--placeholder-->
        
        <div id="copyFooter" class="col-md-6"><!--copyright info-->
            <table class="col-lg-12">
                <tr>
                    <td>&copy; Untitled. All right reserved</td><td>Design: Hippi</td><td>Images: apina.biz</td>
                </tr>
            </table>
        </div>
    
        <div class="col-md-3 col-sm-3 col-xs-3"></div><!--placeholder-->
    
    </footer><!--end of footer-->
    </div><!--end of row-->  
        
    </div><!-- end of container-->

</body>
</html>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>DjangoPollSite</title>
    <meta charset="utf-8">
    
    {% load staticfiles %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/styleResults.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/fonts/css/font-awesome.min.css' %}" />
    
    <script src="{% static 'polls/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'polls/js/jquery-2.1.4.min.js' %}"></script>
    <!--<script src="{% static 'polls/js/jquery-1.11.13.min.js' %}"></script>-->

</head>
    
<body>

    <div id="container" class="container-fluid">
    <div class="row"><!--header row-->
        
    <header id="header" class="col-md-12 col-xs-12">
        
        <nav id="navigator" class="col-md-12">
            <div id="navLeft" class="col-xs-6">
                <a href="foo">Interphase</a>
            </div>
            <div id="navRight" class="col-xs-6">
                <a href="foo">Home</a>
                <a href="foo">Generic</a>
                <a href="foo">Elements</a>
            </div>
        </nav><!--end of nav-->

        <!--<h1>3 Ajankohtaista kysymystä</h1>
        <p>Vastaa ja voita!</p>
        <a href="foo">Aloita tästä</a>-->
        
    </header><!--end of header-->
    </div><!--end of row-->
    
    <div class="row"><!--mainContent row-->
    <article id="mainContent" class="col-md-12 col-xs-12">
        
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        <article id="pollContainer" class="col-md-8"> <!--polls after this!-->
            
            <i id="pollListIcon"class="fa fa-camera-retro fa-3x" ></i>
                
            <h1>{{ question.question_txt }}</h1>

            <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} -- {{ choice.vote }} votes{{ choice.votes|pluralize }}</li>
            {% endfor %}
            </ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
        
        </article><!--end of polls-section-->
        
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        
    </article><!--end of mainContent-->
    </div><!--end of row-->
    
    <div class="row"><!--footer row-->
    <footer id="foot" class="col-lg-12 col-md-12">
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        
        <article class="col-md-8"><!--page info-->
            <div class="col-md-4 col-sm-4 col-xs-4">
                <table>    
                    <th id="footHeader">Lorem Ipsum</th>
                    <tr><td>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                    <tr><td>Höpöhpöpö</td></tr>
                </table>
            </div>
            
            <div class="col-md-4 col-sm-4 col-xs-4">
                <table>    
                    <th>Lorem Ipsum</th>
                    <tr><td>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                    <tr id="footerData"><td>Höpöhpöpö</td></tr>
                </table>
            </div>
            
            <div class="col-md-4 col-sm-4 col-xs-4">
                <table class="col-lg-12">
                    <th>Contact Us</th>
                    <tr>
                        <td id="socialTD">
                            <a id="social" href="http://www.twitter.com" class="fa fa-twitter fa-1x"></a>
                            <a id="social" href="http://www.facebook.com" class="fa fa-facebook fa-1x"></a>
                            <a id="social" href="http://www.plus.google.com" class="fa fa-google-plus fa-1x"></a>
                            <a id="social" href="http://www.pinterest.com" class="fa fa-pinterest fa-1x"></a>
                            <a id="social" href="http://www.linkedin.com" class="fa fa-linkedin fa-1x"></a>
                        </td>
                    </tr>
                    <tr>
                        <th>Address</th>
                        <td id="footerData">Torttukatu 24 </ br>00699 Hinurila</td>
                    </tr>
                    <tr>
                        <th>Mail</th>
                        <td id="footerData">contact@isis.com</td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td id="footerData">0700-allahu</td>
                    </tr>
                </table>
            </div>
        </article><!--end of pageinfo-->
        <div class="col-md-2 col-sm-2 col-xs-2"></div><!--placeholder-->
        
        <div id="copyFooter" class="col-md-12">
            <table>
                <tr>
                    <td>c Untitled. All right reserved</td><td>Design: Hippigay</td><td>Images: apina.biz</td>
                </tr>
            </table>
        </div>
    </footer><!--end of footer-->
    </div><!--end of row-->  
        
    </div><!-- end of container-->

</body>
</html>